version: 2

updates: 
  # Enable version updates for NuGet.

  # Applications:
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the project directory.
    directory: "Items/Applications/Items.ConsoleApp" # Items.ConsoleApp.csproj
    # Check the nuget registry for updates every day (weekdays).
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3

  # Libraries:
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the project directory.
    directory: "Items/Libraries/Items.Common" # Items.Common.csproj
    # Check the nuget registry for updates every day (weekdays).
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3

  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the project directory.
    directory: "Items/Libraries/Items.RollbackEngine" # Items.RollbackEngine.csproj
    # Check the nuget registry for updates every day (weekdays).
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3

  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the project directory.
    directory: "Items/Libraries/Items.StateMachine" # Items.StateMachine.csproj
    # Check the nuget registry for updates every day (weekdays).
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3

  # Tests:
  # No tests projects.
